import time
import re

txt=re.compile(r'fuck|suck')
wish=txt.search('fuck suck mania')
print(wish.group())
wish1=txt.search('suck and fuck mania')
print(wish1.group())
batreg=re.compile(r'bat(bat|cat|mat|man)')
se=batreg.search('batman and batcat')
print(se.group())
print(se.group(1))
text=re.compile(r'bat(wo)?man')
txt1=text.search('batman')
print(txt1.group())
st=re.compile(r'suck(whor)+girl')
st1=st.search('suckwhorgirl')
print(st1.group())
st2=st.search('suckwhorwhorgirl')
print(st2.group())
hareg=re.compile(r'(suck){3}')
ha=hareg.search('sucksucksuck')
print(ha.group())
xmasreg=re.compile(r'\d+\s\w+')
print(xmasreg.findall('12 drummers , 11 pipers,10 roads,9 ladies,8 maids,7swans,6 gees,5 rings'))
vowelreg=re.compile(r'[aeiouAEIOU]')
print(vowelreg.findall('one thing is that the mother fucker bitch sucking my dick without my ambition'))
time.sleep(20)
